### ISSUE TITLE
[bug] 在包含有逻辑的Action行使用内置变量有时候会破坏整行逻辑

### ISSUE THREAD

**Issue by wjhhuizi** [iwxyi/Bilibili-MagicalDanmaku#10]
1.  如图所示，已知判断语句中变量值为真值
![image](https://user-images.githubusercontent.com/10677479/111556746-37075a80-8759-11eb-8438-51f5e8c669d5.png)

2.  测试1，在同行中不使用变量的情况下，逻辑判断正常
![image](https://user-images.githubusercontent.com/10677479/111556821-64ec9f00-8759-11eb-847e-9d6f5bb67c6e.png)

3.  测试2，在同行中使用内置变量的情况下，逻辑判断出现问题
![image](https://user-images.githubusercontent.com/10677479/111556889-96656a80-8759-11eb-9d7f-35de5277ddec.png)

初步怀疑是 内置变量的 % 干扰了逻辑判断中 表达式的 %
辛苦乂桑~

**Comment by iwxyi** [comment]
设置里开启“调试模式”，然后看看为什么没有输出
