### ISSUE TITLE
自定义语音API的问题

### ISSUE THREAD

**Issue by yuki-one** [iwxyi/Bilibili-MagicalDanmaku#16]
能不能出一下如何使用自定义语音API的教程，不想使用讯飞的API但在其它弹幕姬上能使用的自定义语音API填入以后无法使用，使用说明上也没有对此进行介绍

**Comment by iwxyi** [comment]
其他弹幕姬的语音API是怎样的，有例子吗？

**Comment by yuki-one** [comment]
> 其他弹幕姬的语音API是怎样的，有例子吗？

比较简单的接口是通过GET的方式，例如：https://xxx.xxx.com/tts?speak=(待发音字符)&cuid=text&ctp=1&lan=zh&spd=6&pit=5&vol=8000&per=4，接口会返回处理后的音频文件
还有就是通过POST传参，参考其它的弹幕姬例子，可以用一个函数来自动填充发送给接口的文字参数
至于POST传参可以留一个输入框让我们自己键入需要传的参数
附其它弹幕姬例图：
![image](https://user-images.githubusercontent.com/76642580/131285886-7a03423e-e237-46c9-bbc8-7434470bf32b.png)
POST方法：
![image](https://user-images.githubusercontent.com/76642580/131285948-de816335-4c5d-4f02-9eb7-fb2838fd36c3.png)

**Comment by iwxyi** [comment]
`$TTSTEXT` 替换成 `%1`
