### ISSUE TITLE
打开视频流异常

### ISSUE THREAD

**Issue by older-fox** [iwxyi/Bilibili-MagicalDanmaku#2]
显示实时视频流无法载入，在关闭视频窗口后主线程卡死。

另外：AI智能回复如何使用？

**Comment by iwxyi** [comment]
视频这块我也不太清楚
AI智能回复要打开实时弹幕，在收到的弹幕下面出现回复（不是自动发弹幕回复）

**Comment by iwxyi** [comment]
视频流异常可能是因为没有开播，导致无法播放
