### ISSUE TITLE
网易云部分歌曲可以搜索到但是有时候无法播放

### ISSUE THREAD

**Issue by liuzj288** [iwxyi/Bilibili-MagicalDanmaku#23]
能否支持修改网易云自定义解析，比如我想改成这个，[https://github.com/Binaryify/NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)，用本地api也可以减轻服务器的压力

**Comment by iwxyi** [comment]
可以自己修改源码来更换解析
而且现在用的就是这个库

**Comment by liuzj288** [comment]
> 可以自己修改源码来更换解析 而且现在用的就是这个库

本地音乐能支持无损格式吗？flac和ape的

**Comment by iwxyi** [comment]
支持，播放的音质调最高，如果有无损会下载无损的

liuzj288 ***@***.***> 于 2023年3月14日周二 下午3:46写道：
