### ISSUE TITLE
请问如何设置不自动欢迎用户名中带有某些关键词（如“XX网刷人气”）的用户。

### ISSUE THREAD

**Issue by ChaneyChokin** [iwxyi/Bilibili-MagicalDanmaku#26]
由于是小主播直播间，就开了弹幕文字欢迎所有人。但经常有这种广告类型的昵称来直播间，想自己加一些屏蔽用户名昵称的关键词，文档找了一下，也没有看到如何书写这种规则。请大佬指教！

**Comment by iwxyi** [comment]
[%uname% ~ XX网|刷人气]****

名字中带有“XX网”或者“刷人气”的，都不欢迎
多个关键词用|连接

Chaney ***@***.***> 于 2023年5月24日周三 上午10:19写道：

**Comment by ChaneyChokin** [comment]
感谢解惑！
