### ISSUE TITLE
内存占用异常

### ISSUE THREAD

**Issue by uzukizheng** [iwxyi/Bilibili-MagicalDanmaku#28]
为什么内存占用刚启动的时候70M，挂了一周左右会到300M～700M

**Comment by iwxyi** [comment]
估计是哪些地方有内存泄漏了~
可以配合一些内存清理的工具来减掉许多，比如 Mem Reduct

**Comment by uzukizheng** [comment]
> 估计是哪些地方有内存泄漏了~ 可以配合一些内存清理的工具来减掉许多，比如 Mem Reduct

👍 试了下 Mem Reduct 真的减少了好多
