### ISSUE TITLE
新策略影响下无法获取用户名

### ISSUE THREAD

**Issue by yokinanya** [iwxyi/Bilibili-MagicalDanmaku#30]
B站新策略影响下，未登录无法获取用户名，比如张三显示为『张****』，但理论上神奇弹幕应该是带cookie的，但是为什么依旧会出现这种现象

**Comment by iwxyi** [comment]
加群，有最新已解决的内测版

星ノ谷绫沫 ***@***.***> 于 2023年7月4日周二 下午4:41写道：

**Comment by iwxyi** [comment]
最新版v4.10.3已经发布了
