### ISSUE TITLE
mac版好久没更新了，请问可以如何从最新代码编译mac版本

### ISSUE THREAD

**Issue by zhangferry** [iwxyi/Bilibili-MagicalDanmaku#31]
我的是M1设备，下载到的mac包是1年前上传的，而且有bug，想要更新下~

**Comment by lvj5077** [comment]
项目是全开源的，自己用源码编译就可以了

**Comment by tymon42** [comment]
文档里没有找到编译教程，如果有的话方便指下路吗？

**Comment by iwxyi** [comment]
mac版已经更新到release里了

**Comment by iwxyi** [comment]
> 文档里没有找到编译教程，如果有的话方便指下路吗？

1. 下载安装Qt，版本5.13及以后的都可以
2. 编译，好了……
