### ISSUE TITLE
如何像点歌姬一样把点歌信息显示在画面？

### ISSUE THREAD

**Issue by Kotori142857** [iwxyi/Bilibili-MagicalDanmaku#5]
如何像[点歌姬](https://www.danmuji.org/plugins/DGJv3)一样把信息显示在OBS画面？

**Comment by iwxyi** [comment]
可以添加窗口或者截取屏幕，但是做不到透明

**Comment by Kotori142857** [comment]
> 可以添加窗口或者截取屏幕，但是做不到透明

**谢谢**！
不过希望能像点歌姬一样能输出文本。

**Comment by iwxyi** [comment]
> > 可以添加窗口或者截取屏幕，但是做不到透明
> 
> **谢谢**！
> 不过希望能像点歌姬一样能输出文本。

输出文本？列一个列表出来显示在直播界面上马？

**Comment by Kotori142857** [comment]
> > > 可以添加窗口或者截取屏幕，但是做不到透明
> > 
> > 
> > **谢谢**！
> > 不过希望能像点歌姬一样能输出文本。
> 
> 输出文本？列一个列表出来显示在直播界面上马？

点歌姬（https://www.danmuji.org/plugins/DGJv3）用的是输出两个txt供OBS读取——一个是歌曲列表，一个是歌词；小葫芦弹幕点歌

**Comment by Kotori142857** [comment]
> > > 可以添加窗口或者截取屏幕，但是做不到透明
> > 
> > 
> > **谢谢**！
> > 不过希望能像点歌姬一样能输出文本。
> 
> 输出文本？列一个列表出来显示在直播界面上马？

点歌姬 ( https://www.danmuji.org/plugins/DGJv3 ) 用的是在电脑上存储2个txt文件——一个是歌曲状态和列表，一个是歌词——然后供OBS读取。

**Comment by iwxyi** [comment]
> 点歌姬 ( https://www.danmuji.org/plugins/DGJv3 ) 用的是在电脑上存储2个txt文件——一个是歌曲状态和列表，一个是歌词——然后供OBS读取。
> 这是它的 GitHub 仓库: https://github.com/Bililive/DGJv3
原来是这样读的啊，我对OBS读取点歌姬的方式不是很了解。txt文件修改后OBS会自动重新读取吗？
其实我本来打算做成web服务的方式，似乎跨播就是这样做的？

**Comment by iwxyi** [comment]
> 点歌姬 ( https://www.danmuji.org/plugins/DGJv3 ) 用的是在电脑上存储2个txt文件——一个是歌曲状态和列表，一个是歌词——然后供OBS读取。
> 这是它的 GitHub 仓库: https://github.com/Bililive/DGJv3

原来是这样读的啊，我对OBS读取点歌姬的方式不是很了解。txt文件修改后OBS会自动重新读取吗？
其实我本来打算做成web服务的方式，似乎跨播就是这样做的？

**Comment by Kotori142857** [comment]
> 
> 
> > 点歌姬 ( https://www.danmuji.org/plugins/DGJv3 ) 用的是在电脑上存储2个txt文件——一个是歌曲状态和列表，一个是歌词——然后供OBS读取。
> > 这是它的 GitHub 仓库: https://github.com/Bililive/DGJv3
> 
> 原来是这样读的啊，我对OBS读取点歌姬的方式不是很了解。txt文件修改后OBS会自动重新读取吗？
> 其实我本来打算做成web服务的方式，似乎跨播就是这样做的？

OBS是这么读取的，而且TXT文件修改会实时体现在OBS上。

**Comment by iwxyi** [comment]
> > > 点歌姬 ( https://www.danmuji.org/plugins/DGJv3 ) 用的是在电脑上存储2个txt文件——一个是歌曲状态和列表，一个是歌词——然后供OBS读取。
> > > 这是它的 GitHub 仓库: https://github.com/Bililive/DGJv3
> > 
> > 
> > 原来是这样读的啊，我对OBS读取点歌姬的方式不是很了解。txt文件修改后OBS会自动重新读取吗？
> > 其实我本来打算做成web服务的方式，似乎跨播就是这样做的？
> 
> OBS是这么读取的，而且TXT文件修改会实时体现在OBS上。

好的，已经光速加上这个功能了

**Comment by Kotori142857** [comment]
> 
> 
> > > > 点歌姬 ( https://www.danmuji.org/plugins/DGJv3 ) 用的是在电脑上存储2个txt文件——一个是歌曲状态和列表，一个是歌词——然后供OBS读取。
> > > > 这是它的 GitHub 仓库: https://github.com/Bililive/DGJv3
> > > 
> > > 
> > > 原来是这样读的啊，我对OBS读取点歌姬的方式不是很了解。txt文件修改后OBS会自动重新读取吗？
> > > 其实我本来打算做成web服务的方式，似乎跨播就是这样做的？
> > 
> > 
> > OBS是这么读取的，而且TXT文件修改会实时体现在OBS上。
> 
> 好的，已经光速加上这个功能了

**谢谢！**
