### ISSUE TITLE
讯飞在线语音合成无效

### ISSUE THREAD

**Issue by Neomanbeta** [iwxyi/Bilibili-MagicalDanmaku#6]
点击预听以后没有声音，但是在讯飞网站查看在线语音合成控制台里面，今日实时服务量增加了，剩余服务量里面的确也扣除了，这是否是BUG？

**Comment by iwxyi** [comment]
是不是发音人没有填对？
或者调整一下那些声音参数，在某些数值会莫名的没声音

**Comment by Neomanbeta** [comment]
发音人我是直接在程序里选择的，并不是我手动写上去的，我检查过了，没有错误。
另外第一次写进去时候，其实发现API secret和API key里面的值调换了，我手动改了ini，把这个填对了，能正常扣服务量了，但依然没声音。（这个问题我看到你在新的commits里面修复了，那我就等新的build）。
声音参数我没试过改，只改过音量，其它参数是指音调和音速吗？

**Comment by Neomanbeta** [comment]
刚才改动了一下音速，音调，还有音量，然后彻底没有声音了，连选择本地都不播报了，为了避免其它错误影响，我把程序完全删除，从头配置了一次，还是一样的结果，讯飞依然无声，本地是有声的。

**Comment by iwxyi** [comment]
> 发音人我是直接在程序里选择的，并不是我手动写上去的，我检查过了，没有错误。
> 另外第一次写进去时候，其实发现API secret和API key里面的值调换了，我手动改了ini，把这个填对了，能正常扣服务量了，但依然没声音。（这个问题我看到你在新的commits里面修复了，那我就等新的build）。
> 声音参数我没试过改，只改过音量，其它参数是指音调和音速吗？

那可能真的是没发现过的bug了
