### ISSUE TITLE
点歌姬输出的列表建议加上正在播放的歌曲　以及屏蔽歌曲功能

### ISSUE THREAD

**Issue by Kotori142857** [iwxyi/Bilibili-MagicalDanmaku#9]
在`www/music/songs.txt`文件里只有接下来播放的歌曲，没有当前播放的。
同时建议加上歌曲屏蔽的功能。

**Comment by iwxyi** [comment]
当前播放的已经加上了，远程里开启网络服务，直播姬里添加浏览器，网址为“http://localhost:5520/music/playing.html”

**Comment by Kotori142857** [comment]
OK 谢了
